kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-aktivitetskort-publisher
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-aktivitetskort-publisher
        tier: db-f1-micro
        type: POSTGRES_14
        databases:
          - name: amt-aktivitetskort-publisher
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        insights:
          enabled: true
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: amt-arena-acl
        - application: amt-arrangor
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: dev-gcp
        - application: veilarboppfolging
          namespace: poao
          cluster: dev-gcp
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: amt-aktivitetskort-publisher-unleash-api-token
  env:
    - name: AMT_ARENA_ACL_URL
      value: http://amt-arena-acl.amt.svc.cluster.local
    - name: AMT_ARENA_ACL_SCOPE
      value: api://dev-gcp.amt.amt-arena-acl/.default
    - name: AMT_ARRANGOR_SCOPE
      value: api://dev-gcp.amt.amt-arrangor/.default
    - name: AMT_ARRANGOR_URL
      value: http://amt-arrangor
    - name: AKTIVITET_ARENA_ACL_URL
      value: http://aktivitet-arena-acl.dab.svc.cluster.local
    - name: AKTIVITET_ARENA_ACL_SCOPE
      value: api://dev-gcp.dab.aktivitet-arena-acl/.default
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao
    - name: VEILEDERURL_BASEPATH
      value: https://veilarbpersonflate.intern.dev.nav.no/arbeidsmarkedstiltak/deltakelse/deltaker
    - name: DELTAKERURL_BASEPATH
      value: https://amt.intern.dev.nav.no/arbeidsmarkedstiltak

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
