kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-aktivitetskort-publisher
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-aktivitetskort-publisher
        type: POSTGRES_14
        tier: db-custom-2-5120
        databases:
          - name: amt-aktivitetskort-publisher
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: true
        insights:
          enabled: true
  port: 8080
  ingresses:
    - https://amt-aktivitetskort-publisher.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      rules:
        - application: amt-arena-acl
          namespace: amt
          cluster: prod-gcp
        - application: aktivitet-arena-acl
          namespace: dab
          cluster: prod-gcp
  env:
    - name: AMT_ARENA_ACL_URL
      value: http://amt-arena-acl.amt.svc.cluster.local
    - name: AMT_ARENA_ACL_SCOPE
      value: api://prod-gcp.amt.amt-arena-acl/.default
    - name: AKTIVITET_ARENA_ACL_URL
      value: http://aktivitet-arena-acl.dab.svc.cluster.local
    - name: AMT_ARENA_ACL_SCOPE
      value: api://prod-gcp.dab.aktivitet-arena-acl/.default
